# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 241c3cc3e449c8a0e07d72494dd2d7c9cec15de740d65853c78f1fcbbb9a857a799631ddd18eb33c5636aee2b29650ef9353914d11604347780e3985930aaf28

test:
  secret_key_base: b5d70dcac30473d5a8bf3d0fb94c420e5fd71675bd73b107ed4641f618f14518fbf01f3ac6737b93aa935705b0e6b1a1f993dbdb8209dc36b9d935bb128da512

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
